---
- hosts: all
  sudo: yes
  vars:
    dev_packages:
      - cmake
      - make
      - g++
      - clang
      - bear
      - git
    jenkins_plugins:
      - git
      - ssh
      - pmd
      - ws-cleanup
  roles:
  - geerlingguy.jenkins
  - UnrealQuester.oclint
  - tools
