---
- hosts: all
  sudo: yes
  vars:
    dev_packages:
      - cmake
      - make
      - g++
      - clang
      - bear
      - git
    jenkins_plugins:
      - git
      - ssh
      - pmd
      - ws-cleanup
    gitlab_external_url: "http://gitlab:8081"
    jenkins_http_port: 8082
  roles:
  - geerlingguy.jenkins
  - UnrealQuester.oclint
  - tools
  - geerlingguy.gitlab
