---
- hosts: all
  sudo: yes
  vars:
    dev_packages:
      - cmake
      - make
      - g++
      - clang
      - bear
      - git
  roles:
  - geerlingguy.jenkins
  - UnrealQuester.oclint
  - tools
