---
- hosts: all
  sudo: yes
  vars:
    dev_packages:
      - cmake
      - make
      - g++
      - clang
      - bear
      - git
    gitlab_external_url: "http://localhost:8081"
  roles:
  - UnrealQuester.oclint
  - tools
  - geerlingguy.gitlab
